[project]
name = "aitdrs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "confluent-kafka>=2.13.0",
  "fastapi>=0.128.0",
  "fastparquet>=2025.12.0",
  "httpx>=0.28.1",
  "numpy>=2.4.1",
  "pandas>=2.3.3",
  "prometheus-client>=0.24.1",
  "pyarrow>=23.0.0",
  "pydantic>=2.12.5",
  "pydantic-settings>=2.12.0",
  "python-dotenv>=1.2.1",
  "pyyaml>=6.0.3",
  "ruff>=0.14.13",
  "scikit-learn>=1.8.0",
  "slowapi>=0.1.9",
  "structlog>=25.5.0",
  "tqdm>=4.67.1",
  "uvicorn>=0.40.0",
  "xgboost>=3.1.3",
]

[project.optional-dependencies]
dev = [
  "ipykernel>=7.1.0",
  "pytest>=9.0.2",
  "pytest-asyncio>=1.3.0",
  "pytest-cov>=7.0.0",
]
